version: "3.7"
services:
  # client:
  #   build: ./client
  #   ports:
  #     - "8082:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.development
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/home/node/app
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - "21017:21017"
    volumes:
      - .data/mongo:/data/db

