version: "3.7"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    container_name: gaivota-client
    ports:
      - "5001:5001"
    volumes:
      - ./client:/home/node/app
    command: npm run start
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.development
    container_name: gaivota-server
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/home/node/app
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "21017:21017"
    volumes:
      - .data/mongo:/data/db

